server:
  port: 8083

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5432/catalogdb
    username: postgres
    password: postgres

  flyway:
    enabled: true
    # set this to where your SQL files actually are:
    # if files are in src/main/resources/db/migration -> use classpath:db/migration
    # if files are directly in src/main/resources/db -> use classpath:db
    locations: classpath:db
    check-location: true
    baseline-on-migrate: true
    clean-disabled: true   # DEV ONLY; remove after first successful run
    # clean-on-validation-error: true  # optional for messy states

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # optional (Hibernate 6 auto-detects):
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.flywaydb: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka