server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: pet-service
              uri: lb://pet-service
              predicates:
                - Path=/pets/**
            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/service-types/**,/providers/**
            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/bookings/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.furryhub.gateway: DEBUG

# Optional: easiest on/off switch for Spring Security debug
spring.security.debug: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka